DROP DATABASE IF EXISTS greenbar;
CREATE DATABASE IF NOT EXISTS greenbar
	DEFAULT CHARACTER   SET utf8;
USE greenbar;

CREATE TABLE 商品表
(
商品编号	VARCHAR(255)	NOT NULL	PRIMARY KEY,
产品名	VARCHAR(255)	NOT NULL,
原价	FLOAT	NOT NULL,
库存	INT	UNSIGNED	NOT NULL,
现价	FLOAT	NOT NULL,
图片	BLOB	DEFAULT NULL,
主类别	VARCHAR(8)	NOT NULL,
次类别	VARCHAR(16)	NOT NULL
);
CREATE TABLE 用户
(
用户名	VARCHAR(255)	NOT NULL	PRIMARY KEY,
头像	BLOB	DEFAULT NULL,
真实姓名	VARCHAR(255)	NOT NULL,
邮政编码	VARCHAR(255)	NOT NULL,
联系电话	VARCHAR(64)	NOT NULL,
电子邮箱	VARCHAR(255)	NOT NULL,
密码	VARCHAR(255)	NOT NULL,
收货地址	VARCHAR(255)	NOT NULL,
UNIQUE (联系电话),
UNIQUE (电子邮箱)
);
CREATE TABLE 购物车
(
用户名	VARCHAR(255)	NOT NULL,
商品编号	VARCHAR(255)	NOT NULL,
数量	INT	UNSIGNED	NOT NULL,
PRIMARY KEY (用户名,商品编号),
FOREIGN KEY (商品编号)
    REFERENCES 商品表 (商品编号)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
FOREIGN KEY (用户名)
    REFERENCES 用户 (用户名)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
CREATE TABLE 历史订单
(
订单编号	BIGINT  UNSIGNED	NOT NULL	PRIMARY KEY,
日期	DATETIME	NOT NULL,
用户名	VARCHAR(255)	NOT NULL,
状态	VARCHAR(16)	NOT NULL,
金额	FLOAT	NOT NULL,
评价	TEXT	NOT NULL,
FOREIGN KEY (用户名)
    REFERENCES 用户 (用户名)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
CREATE TABLE 用户留言
(
用户名	VARCHAR(255)	NOT NULL,
作者用户名	VARCHAR(255)	NOT NULL,
时间	DATETIME	NOT NULL,
状态	VARCHAR(16)	NOT NULL,
标题	VARCHAR(255)	NOT NULL,
内容	TEXT	NOT NULL,
PRIMARY KEY (作者用户名,时间),
FOREIGN KEY (用户名)
    REFERENCES 用户 (用户名)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
FOREIGN KEY (作者用户名)
    REFERENCES 用户 (用户名)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
CREATE TABLE 游记
(
时间	DATETIME	NOT NULL,
作者用户名	VARCHAR(255)	NOT NULL,
类型	VARCHAR(16)	NOT NULL,
精华	TINYINT(1)  DEFAULT 0,
内容	TEXT	NOT NULL,
标题	VARCHAR(255)	NOT NULL,
PRIMARY KEY (作者用户名,时间),
FOREIGN KEY (作者用户名)
    REFERENCES 用户 (用户名)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
CREATE TABLE 帖子
(
帖子编号	BIGINT  UNSIGNED	NOT NULL	PRIMARY KEY,
作者用户名	VARCHAR(255)	NOT NULL,
最后回复查看用户名	VARCHAR(255)	NOT NULL,
内容	TEXT	NOT NULL,
发表时间	DATETIME	NOT NULL,
类型	VARCHAR(16)	NOT NULL,
标题	VARCHAR(255)	NOT NULL,
FOREIGN KEY (作者用户名)
    REFERENCES 用户 (用户名)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
FOREIGN KEY (最后回复查看用户名)
    REFERENCES 用户 (用户名)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
CREATE TABLE 帖子回复
(
作者用户名	VARCHAR(255)	NOT NULL,
时间	DATETIME	NOT NULL,
帖子编号	 BIGINT UNSIGNED	NOT NULL,
内容	TEXT	NOT NULL,
PRIMARY KEY (作者用户名,时间),
FOREIGN KEY (作者用户名)
    REFERENCES 用户 (用户名)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
FOREIGN KEY (帖子编号)
    REFERENCES 说说话 (帖子编号)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);