DROP DATABASE IF EXISTS YGGL;
CREATE DATABASE IF NOT EXISTS YGGL
	DEFAULT CHARACTER   SET utf8;
USE YGGL;
CREATE TABLE employees
(
	员工编号	CHAR(6)	NOT NULL PRIMARY KEY,
	姓名	CHAR(10)	NOT NULL,
	学历	CHAR(4)	NOT NULL,
	出生日期	DATE	NOT NULL,
	性别	CHAR(2)	NOT NULL,
	工作年限	TINYINT	NOT NULL	DEFAULT 0,
	地址	VARCHAR(20),
	电话号码	CHAR(11),
	员工部门号	CHAR(3)	NOT NULL
);
CREATE TABLE emptest
(
	姓名	CHAR(10)	NOT NULL,
	出生日期	DATE	NOT NULL	,
	工龄工资	FLOAT(8,2)	NOT NULL,
	CHECK(出生日期<'1995-01-01')
);
CREATE TABLE departments
(
	部门编号	CHAR(3)	NOT NULL	PRIMARY KEY,
	部门名称	CHAR(20)	NOT NULL,
	备注	TEXT
);
CREATE TABLE salary
(
	员工编号	CHAR(6)	NOT NULL	PRIMARY KEY,
	收入	FLOAT(8,2)	NOT NULL,
	支出	FLOAT(8,2)	NOT NULL,
	FOREIGN KEY(员工编号)
		REFERENCES employees(员工编号)
			ON DELETE RESTRICT
			ON UPDATE RESTRICT
);
CREATE TABLE bonus
(
	员工编号	CHAR(6)	NOT NULL PRIMARY KEY,
	奖金	FLOAT(8,2)	NOT NULL,
	FOREIGN KEY(员工编号)
		REFERENCES employees(员工编号)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);

ALTER TABLE employees
	ADD CHECK(工作年限>0 AND 工作年限<30);
ALTER TABLE employees
	ADD
	FOREIGN KEY(员工部门号)
		REFERENCES departments(部门编号)
			ON DELETE CASCADE
			ON UPDATE CASCADE;